# UI 텍스트 현지화 / UI Text Localization
STRINGS = {
    'ko': {
        "select_language": "언어를 선택하세요 (1: 한국어, 2: English): ",
        "invalid_input": "잘못된 입력입니다. 1 또는 2를 입력하세요.",
        "mode_selected": "\n'{lang_upper}' 모드로 실행합니다. 프롬프트 파일: '{prompt_filepath}'",
        "fetching_models": "🤖 OpenRouter에서 최신 모델 정보를 가져오는 중...",
        "fetching_models_done": "✅ 모델 정보 로드 완료.",
        "fetching_models_failed": "⚠️ 모델 정보 로드 실패. 기본 설정으로 계속합니다.",
        "error_no_models": "오류: '{filepath}'에 사용할 모델이 지정되지 않았음.",
        "error_file_not_found": "오류: '{filepath}' 파일을 찾을 수 없음.",
        "error_no_headers": "오류: '{filepath}'에서 '## 섹션명 ##' 형식의 헤더를 찾을 수 없음.",
        "error_no_project_name": "오류: 프롬프트 파일에 '## project name ##' 섹션이 반드시 포함되어야 합니다.",
        "error_no_system_prompt":"오류: 프롬프트 파일에 '## system prompt ##' 섹션이 반드시 포함되어야 합니다.",
        "error_no_api_key": "오류: .env 파일에 OPENROUTER_API_KEY가 설정되지 않았음.",
        "research_start": "🚀 프로젝트 '{project_name}' 작업을 시작합니다. (백그라운드 로깅 전용)",
        "output_folder_info": "📂 결과는 '{output_dir}' 폴더에 저장됩니다.",
        "live_log_info": "👁️  실시간 로그는 `python view_log.py`로 확인하세요.",
        "models_in_use": "🤖 사용할 모델: {models_list}",
        "collaboration_disabled": "🤝 AI 협업 기능이 비활성화되었습니다.",
        "prompt_execution": "▶️ 프롬프트 {prompt_id}/{total_prompts} 실행: {prompt_name}",
        "reasoning_activated": "   ✨ Reasoning 모드가 활성화되었습니다.",
        "request_start": "   (총 {num_models}개 모델에 동시 요청 및 로깅 시작...)",
        "log_prompt_header": "\n\n{divider} 프롬프트 {prompt_id} ({prompt_name}) {divider}\n\n",
        "log_reasoning_header": "\n--- [생각 과정] ---\n",
        "log_error_header": "\n\n--- 오류 ---\n{error_message}\n",
        "log_error_message": "오류 발생: {e}",
        "task_completed": "✅ '{nick}' 작업 완료.",
        "task_failed": "❌ '{nick}' 작업 실패.",
        "task_error": "❌ '{model_nickname}' 작업 처리 중 최종 오류: {e}",
        "prompt_finished": "\n--- 프롬프트 {prompt_id} 모든 작업 완료 ---",
        "all_finished": "✅ 모든 작업 과정이 완료되었습니다.",
        "select_bot": "\n어떤 작업을 시작할까요?",
        "bot_option_research": "[1] 리서치 봇 실행 (기본값)",
        "bot_option_custom": "[2] 다른 프롬프트 파일 지정",
        "enter_prompt_filename": "prompts/ 폴더 안에 있는 파일명을 입력하세요 (예: my_custom_task.md): ",
    },
    'en': {
        "select_language": "Select language (1: 한국어, 2: English): ",
        "invalid_input": "Invalid input. Please enter 1 or 2.",
        "mode_selected": "\nRunning in '{lang_upper}' mode. Prompt file: '{prompt_filepath}'",
        "fetching_models": "🤖 Fetching latest model information from OpenRouter...",
        "fetching_models_done": "✅ Model information loaded successfully.",
        "fetching_models_failed": "⚠️ Failed to fetch model information. Proceeding with default settings.",
        "error_no_models": "Error: No models specified in '{filepath}'.",
        "error_file_not_found": "Error: File not found at '{filepath}'.",
        "error_no_headers": "Error: Could not find headers in '## Section ##' format in '{filepath}'.",
        "error_no_project_name": "Error: The prompt file must contain a '## project name ##' section.",
        "error_no_system_prompt": "Error: The prompt file must contain a '## system prompt ##' section.",
        "error_no_api_key": "Error: OPENROUTER_API_KEY is not set in the .env file.",
        "research_start": "🚀 Starting task for project '{project_name}'. (Background Logging Only)",
        "output_folder_info": "📂 Results will be saved in the '{output_dir}' folder.",
        "live_log_info": "👁️  Check live logs with `python view_log.py`.",
        "models_in_use": "🤖 Models in use: {models_list}",
        "collaboration_disabled": "🤝 AI collaboration is disabled.",
        "prompt_execution": "▶️ Executing Prompt {prompt_id}/{total_prompts}: {prompt_name}",
        "reasoning_activated": "   ✨ Reasoning mode activated.",
        "request_start": "   (Starting concurrent requests and logging for {num_models} models...)",
        "log_prompt_header": "\n\n{divider} PROMPT {prompt_id} ({prompt_name}) {divider}\n\n",
        "log_reasoning_header": "\n--- [REASONING PROCESS] ---\n",
        "log_error_header": "\n\n--- ERROR ---\n{error_message}\n",
        "log_error_message": "Error occurred: {e}",
        "task_completed": "✅ Task for '{nick}' completed.",
        "task_failed": "❌ Task for '{nick}' failed.",
        "task_error": "❌ Final error while processing task for '{model_nickname}': {e}",
        "prompt_finished": "\n--- All tasks for Prompt {prompt_id} are complete ---",
        "all_finished": "✅ All processes have been completed.",
        "select_bot": "\nWhich task would you like to start?",
        "bot_option_research": "[1] Run Research Bot (Default)",
        "bot_option_custom": "[2] Specify a different prompt file",
        "enter_prompt_filename": "Enter the filename located in the prompts/ folder (e.g., my_custom_task.md): ",
    }
}
